#Redisson配置
singleServerConfig:
  address: "redis://47.102.116.11:6378"
  password: null
  clientName: null
  database: 0 #选择使用哪个数据库0~15
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  subscriptionsPerConnection: 5
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  dnsMonitoringInterval: 5000

threads: 0
nettyThreads: 0
codec:
  class: "org.redisson.client.codec.StringCodec"   #默认序列化方式 此处为字符串
transportMode: "NIO"